name: Testing üë®‚Äçüî¨

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '*.md'
      - '*.nimble'
      - '*.json'
      - '.gitignore'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - '*.md'
      - '*.nimble'
      - '*.json'
      - '.gitignore'
      - 'LICENSE'


jobs:
  nim:
    name: Nim
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        nim-version:
          - '2.2.0'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.nimble
            .nim_runtime
          key: ${{ runner.os }}-nimble-v2-${{ hashFiles('*.nimble') }}
      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: ${{ matrix.nim-version }}
      - name: Run console
        run: |
          nim c -r -d:danger --hints:off --warnings:off --checks:off console/nim/why.nim

  python:
    name: Python
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.13'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run console
        run: |
          python console/python3/why.py

  erlang:
    runs-on: ubuntu-latest
    name: Erlang
    steps:
      - uses: actions/checkout@v4
      - name: Setup erlang
        run: |
          sudo apt update
          sudo apt install erlang
      - name: Run console
        run: |
          cd console/erlang
          echo "c(why), why:why()." | erl -s init stop

  csharp:
    runs-on: ubuntu-latest
    name: C#
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Run console
        run: |
          dotnet tool install -g dotnet-script
          cd console/csharp
          mono-csc why.cs -unsafe
          mono why.exe

  javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run JavaScript file
        run: |
          cd console/js
          node why.js

  typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install TypeScript
        run: |
          npm i -g tsx
      - name: Compile and run TypeScript file
        run: |
          cd console/ts
          tsx why.js
